name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install gcloud SDK
      run: |
        sudo apt-get update && sudo apt-get install google-cloud-sdk
    - name: Activate Service Account 
      env: 
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "$GCLOUD_AUTH" | base64 --decode > "$HOME"/gcloud.json
        sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
    - name: Deploy Function 
      run: |
        gcloud functions deploy earlyEmailSignup --project uwenca --service-account github-actions@uwenca.iam.gserviceaccount.com
